"""
Report Generator - Generates TODO.md files from compliance issues
"""
from datetime import datetime
from typing import List

class ReportGenerator:
    """Generates TODO.md reports from compliance check results"""
    
    def generate_todo(self, repository_url: str, branch: str, issues: List[dict]) -> str:
        """
        Generate TODO.md content
        
        Args:
            repository_url: URL of analyzed repository
            branch: Branch that was analyzed
            issues: List of compliance issues
            
        Returns:
            TODO.md content as string
        """
        # Count issues by severity
        critical = [i for i in issues if i['severity'] == 'critical']
        high = [i for i in issues if i['severity'] == 'high']
        medium = [i for i in issues if i['severity'] == 'medium']
        low = [i for i in issues if i['severity'] == 'low']
        
        # Generate report
        lines = [
            "# TODO: Spec Compliance Issues",
            "",
            f"**Generated**: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC",
            f"**Repository**: {repository_url}",
            f"**Branch**: {branch}",
            f"**Total Issues**: {len(issues)}",
            "",
            "## Summary",
            "",
            f"- **Critical**: {len(critical)}",
            f"- **High**: {len(high)}",
            f"- **Medium**: {len(medium)}",
            f"- **Low**: {len(low)}",
            ""
        ]
        
        # Add critical issues
        if critical:
            lines.extend(self._format_issues("Critical Issues", critical))
        
        # Add high priority issues
        if high:
            lines.extend(self._format_issues("High Priority Issues", high))
        
        # Add medium priority issues
        if medium:
            lines.extend(self._format_issues("Medium Priority Issues", medium))
        
        # Add low priority issues
        if low:
            lines.extend(self._format_issues("Low Priority Issues", low))
        
        # Add recommendations
        lines.extend([
            "",
            "## Recommendations",
            "",
            "1. **Address Critical Issues First**: Focus on critical severity issues as they may represent security vulnerabilities or major functional gaps.",
            "2. **Review High Priority Items**: High priority issues indicate missing or incorrect implementations of important requirements.",
            "3. **Plan for Medium/Low Items**: Schedule medium and low priority items for future sprints.",
            "4. **Update Specifications**: If any flagged items are intentional deviations, update the specifications to reflect the current design.",
            "5. **Re-run Compliance Check**: After addressing issues, run the compliance checker again to verify fixes.",
            "",
            "---",
            "",
            f"*This report was automatically generated by the Spec Compliance Checker Service*"
        ])
        
        return "\n".join(lines)
    
    def _format_issues(self, section_title: str, issues: List[dict]) -> List[str]:
        """Format a section of issues"""
        lines = [
            f"## {section_title} ({len(issues)})",
            ""
        ]
        
        for i, issue in enumerate(issues, 1):
            lines.extend([
                f"### {i}. {issue.get('title', 'Untitled Issue')}",
                "",
                f"- **Severity**: {issue['severity'].capitalize()}",
                f"- **Type**: {issue.get('type', 'unknown').replace('_', ' ').title()}",
            ])
            
            if 'spec_file' in issue:
                lines.append(f"- **Spec Reference**: {issue['spec_file']}")
            
            if 'requirement_id' in issue:
                lines.append(f"- **Requirement**: {issue['requirement_id']}")
            
            if 'file' in issue:
                lines.append(f"- **File**: {issue['file']}")
            
            if 'files_checked' in issue:
                lines.append(f"- **Files Checked**: {issue['files_checked']}")
            
            if 'description' in issue:
                lines.extend([
                    "",
                    f"**Description**: {issue['description']}",
                ])
            
            if 'requirement_text' in issue:
                lines.extend([
                    "",
                    f"**Requirement Text**: {issue['requirement_text']}",
                ])
            
            if 'current_state' in issue:
                lines.extend([
                    "",
                    f"**Current State**: {issue['current_state']}",
                ])
            
            if 'expected_state' in issue:
                lines.extend([
                    "",
                    f"**Expected State**: {issue['expected_state']}",
                ])
            
            if 'suggestion' in issue:
                lines.extend([
                    "",
                    f"**Suggestion**: {issue['suggestion']}",
                ])
            
            if 'example' in issue:
                lines.extend([
                    "",
                    "**Example**:",
                    "```",
                    issue['example'],
                    "```",
                ])
            
            lines.append("")
        
        return lines
